server:
  port: 8088
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:mysql://rm-uf6x20q6774e054o05o.mysql.rds.aliyuncs.com:3306/jy-out-dev?setUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    username: jyzg
    password: aw%iy8PGJA9H
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    default-statement-timeout: 60
  mapper-locations: classpath*:/mapper/*.xml

logging:
  level:
    com.zhuzi.mapper: debug